# Generated by Django 6.0 on 2025-12-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_task_is_recurring_task_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_occurrence',
            field=models.OneToOneField(blank=True, help_text='Link to the next occurrence of this recurring task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_occurrence', to='todo_app.task'),
        ),
    ]
