# Generated by Django 6.0 on 2026-04-30

from django.conf import settings
from django.db import migrations, models


def assign_legacy_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Category = apps.get_model('todo_app', 'Category')
    Tag = apps.get_model('todo_app', 'Tag')
    Task = apps.get_model('todo_app', 'Task')
    ChatMessage = apps.get_model('todo_app', 'ChatMessage')

    legacy_user, _ = User.objects.get_or_create(
        username='legacy_user',
        defaults={'is_active': True}
    )

    Category.objects.filter(user__isnull=True).update(user=legacy_user)
    Tag.objects.filter(user__isnull=True).update(user=legacy_user)
    Task.objects.filter(user__isnull=True).update(user=legacy_user)
    ChatMessage.objects.filter(user__isnull=True).update(user=legacy_user)


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_task_next_occurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='todo_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='todo_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='todo_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='todo_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(assign_legacy_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='todo_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='todo_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='todo_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='todo_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_tag_per_user'),
        ),
    ]
