# Generated by Django 6.0.4 on 2026-04-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_multi_user_isolation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
